spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/**
          filters:
            - AuthenticationFilter
server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
